#!/usr/bin/env python3
import paramiko

hostname = "192.168.0.37"
username = "sshd"
password = "PASSWORD"

commands = [
"netstat -tun | grep -v '127.0.0.1\|192.168.0.15' | awk '{print $6}' | sort | uniq -c | sort -n | grep ESTABLISHED | awk '{print $1}'"
]

#monitor = [
#"netstat -tun | grep -v '127.0.0.1\|192.168.0.15' | uniq -c | sort -n"
#]

actions = ("sudo poweroff")

# initialize the SSH client
client = paramiko.SSHClient()
# add to known hosts
client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
try:
    client.connect(hostname=hostname, username=username, password=password)
except IndexError:
    print("[!] Cannot connect to the SSH Server")
    exit()
# execute the commands
for command in commands:
#    print("="*50, command, "="*50)
    stdin, stdout, stderr = client.exec_command(command)
    conn = int(stdout.read().decode())
    if conn < 3:
        print("There are less than ({})".format(conn),"connections. This program will now deploy: <{}>".format(actions), "command using SSH."),
        stdin, stdout, stderr = client.exec_command(actions)
    else:
        print("There are more than ({})".format(conn),"connections. This log for temporarily monitoring only and can be removed later")
    err = stderr.read().decode()
    if err:
        print(err)
